def REPO_URL = 'https://github.com/kaveenabeywansa/ionic-templates.git';
def REPO_BRANCH = 'master';

pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello Superman Preprod !'
                sh "pwd"
            }
        }

        stage('SCM') {
            steps {
                dir("${project}/PREPROD") {
                    git(
                        url: "${REPO_URL}",
                        branch: "${REPO_BRANCH}"
                    )
                }
            }
        }

        stage('RunFastlane') {
            steps {
                dir("Buildtool") {
                    sh "bundle exec fastlane build_test_lane"
                }
            }
        }

        stage('End') {
            steps {
                echo 'End of Job !'
            }
        }
    }
}
