def REPO_URL = 'https://github.com/kaveenabeywansa/ionic-templates.git';
def REPO_BRANCH = 'master';

pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello Batman Preprod !'
            }
        }

        stage('SCM') {
            steps {
                git(
                    url: "${REPO_URL}",
                    branch: "${REPO_BRANCH}"
                )
            }
        }

        stage('End') {
            steps {
                echo 'End of Job !'
            }
        }
    }
}
